name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing to master/main
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your PAT with repo + read:user + read:org permissions
          token: ${{ secrets.API_KEY }}

          # Base content
          base: header, activity, community, repositories, metadata

          # Languages plugin (recent usage)
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          # Notable repos plugin
          plugin_notable: yes
          plugin_notable_filter: stars:>=1
          commits_authoring: muhammadrafayasif, email1@example.com, email2@example.com

          # Output file
          filename: metrics.svg
