name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.API_KEY }}

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14

          plugin_notable: yes
          plugin_notable_filter: stars>3
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_exclude: first-contributions
          commits_authoring: muhammadrafayasif, muhammadrafay3561@gmail.com, rafay4730069@cloud.neduet.edu.pk

          filename: metrics.svg
